# --- !Ups

create table "specialities" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "speciality" varchar not null
);

INSERT INTO specialities(id, speciality)
	VALUES (1, 'Pediatrics'),
	(2, 'Family Practice'),
	(3, 'Urgent Care Medicine');



# --- !Downs

drop table "specialities" if exists;
