# --- !Ups

create table "addresses" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "address1" varchar not null,
  "address2" varchar not null,
  "phone" varchar not null,
  "zip_code" varchar not null,
  "latitude" decimal not null,
  "longitude" decimal not null,
  "user_id" bigint not null REFERENCES users("id"),
  "created_at" timestamp default current_timestamp,
  "updated_at" timestamp default current_timestamp
);

INSERT INTO addresses(address1, address2, phone, zip_code, latitude, longitude, user_id)
	VALUES ('12721 Bass Lake Rd', 'Maple Grove, MN', '7635592861', '55361', 1, 1, 2),
	('12722 Bass Lake Rd', 'Maple Grove, MN', '7635592862', '55362', 1, 1, 3),
	('12723 Bass Lake Rd', 'Maple Grove, MN', '7635592863', '55363', 1, 1, 4),
	('12724 Bass Lake Rd', 'Maple Grove, MN', '7635592864', '55364', 1, 1, 5),
	('12725 Bass Lake Rd', 'Maple Grove, MN', '7635592865', '55365', 1, 1, 6);

# --- !Downs

drop table "addresses" if exists;
