# --- !Ups

create table "services" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "service" varchar not null,
  "doctor_id" bigint not null REFERENCES users("id"),
  "minimum_cost" decimal default 0,
  "maximum_cost" decimal default 0,
  "created_at" timestamp default current_timestamp,
  "updated_at" timestamp default current_timestamp
);

INSERT INTO services(service, doctor_id, minimum_cost, maximum_cost)
	VALUES ('Services Office Visit - Primary Doctor - Established Patient - High Complexity', 2, 302, 377),
	( 'Office Visit - Primary Doctor - Established Patient - Minimal Complexity', 2, 42, 52),
	( 'Office Visit - Primary Doctor - Established Patient - Moderate Complexity', 2, 145, 188),
	( 'Office Visit - Primary Doctor - New Patient - High Complexity', 2, 420, 550),
	( 'Services Office Visit - Primary Doctor - Established Patient - High Complexity', 3, 302, 377),
  ( 'Office Visit - Primary Doctor - Established Patient - Minimal Complexity', 3, 42, 52),
  ( 'Office Visit - Primary Doctor - Established Patient - Moderate Complexity', 3, 145, 188),
  ( 'Services Office Visit - Primary Doctor - Established Patient - High Complexity', 4, 302, 377),
  ( 'Office Visit - Primary Doctor - Established Patient - Minimal Complexity', 5, 42, 52),
  ( 'Office Visit - Primary Doctor - Established Patient - Moderate Complexity', 6, 145, 188),
  ( 'Office Visit - Primary Doctor - New Patient - High Complexity', 6, 420, 550);

# --- !Downs

drop table "services" if exists;
